<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ xnat-data-models: src/main/resources/schemas/xnat/xnat.xsd
  ~ XNAT http://www.xnat.org
  ~ Copyright (c) 2017, Washington University School of Medicine
  ~ All Rights Reserved
  ~
  ~ Released under the Simplified BSD.
  ~ modified by Choon, SingHealth Data Science, Innovation and Research Platforms (SDIRP) for SC (DICOM Modality Secondary Capture)
  -->
<xs:schema targetNamespace="http://nrg.wustl.edu/xnat" xmlns:xnat="http://nrg.wustl.edu/xnat" xmlns:prov="http://www.nbirn.net/prov" xmlns:xdat="http://nrg.wustl.edu/xdat" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:import namespace="http://www.nbirn.net/prov" schemaLocation="../birn/birnprov.xsd"/>
	<xs:import namespace="http://nrg.wustl.edu/xdat" schemaLocation="../xdat/xdat.xsd"/>
	<xs:element name="PHOTOACOUSTICIMAGINGSession" type="xnat:photoacousticimagingSessionData"/>

	<xs:complexType name="photoacousticimagingSessionData">
		<xs:annotation>
			<xs:documentation>Secondary Capture Session</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="xnat:imageSessionData"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="photoacousticimagingScanData">
		<xs:annotation>
			<xs:documentation>Secondary Capture Scan</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="xnat:imageScanData">
				<xs:sequence minOccurs="0">
					<xs:element name="parameters" minOccurs="0">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="addParam" type="xnat:addField" minOccurs="0" maxOccurs="unbounded">
									<xs:annotation>
										<xs:appinfo>
											<xdat:field>
												<xdat:relation uniqueComposite="PHOTOACOUSTICIMAGING_SCAN"/>
											</xdat:field>
										</xs:appinfo>
									</xs:annotation>
								</xs:element>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
</xs:schema>